export interface Consultation {
  id: string;
  title: string;
  projectNumber: string;
  proposer: string;
  status: 'W trakcie konsultacji' | 'Opiniowanie' | 'Zakończone' | 'Prekonsultacje';
  startDate: string;
  endDate: string;
  description: string;
  type: 'krajowe' | 'samorządowe';
  city?: string;
  institution?: string;
  institutionType?: 
    | 'gmina' 
    | 'powiat' 
    | 'województwo' 
    | 'miasto na prawach powiatu'
    | 'Administracja Rządowa'
    | 'Urząd Wojewódzki'
    | 'Starostwo Powiatowe'
    | 'Kuratorium Oświaty'
    | 'Inspektorat'
    | 'Inne instytucje publiczne';
  tags: Array<{ name: string; variant: 'default' | 'secondary' | 'outline' | 'destructive' }>;
  popularity: number;
  documents: Array<{
    name: string;
    type: 'Projekt ustawy' | 'Uzasadnienie' | 'OSR' | 'Inne';
    url: string;
  }>;
  region?: string;
}

export const consultationsData: Consultation[] = [
  // PREKONSULTACJE SEJMOWE - NAJPOPULARNIEJSZE
  {
    id: 'pre-1',
    title: 'Projekt ustawy o zmianie ustawy o wychowaniu w trzeźwości i przeciwdziałaniu alkoholizmowi',
    projectNumber: 'UD204',
    proposer: 'Rada Ministrów',
    status: 'Prekonsultacje',
    startDate: '2025-12-01',
    endDate: '2025-12-21',
    description: 'Projekt zakłada wprowadzenie zakazu sprzedaży napojów energetycznych osobom poniżej 16. roku życia oraz nakłada obowiązek weryfikacji wieku przez sprzedawcę.',
    type: 'krajowe',
    tags: [
      { name: 'Zdrowie', variant: 'default' },
      { name: 'Handel', variant: 'secondary' },
    ],
    popularity: 9500,
    documents: [
      { name: 'Projekt ustawy', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
      { name: 'Ocena Skutków Regulacji', type: 'OSR', url: '#' },
    ],
  },
  {
    id: 'pre-2',
    title: 'Poselski projekt ustawy o zmianie ustawy Kodeks pracy',
    projectNumber: 'Druk nr 55',
    proposer: 'Grupa posłów KP Polska 2050',
    status: 'Prekonsultacje',
    startDate: '2025-11-25',
    endDate: '2025-12-15',
    description: 'Wprowadzenie 4-dniowego tygodnia pracy jako opcji do wyboru przez pracodawcę i pracownika. Projekt zakłada elastyczne formy organizacji czasu pracy.',
    type: 'krajowe',
    tags: [
      { name: 'Praca', variant: 'default' },
      { name: 'Prawo pracy', variant: 'secondary' },
    ],
    popularity: 8700,
    documents: [
      { name: 'Projekt ustawy', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
    ],
  },
  {
    id: 'pre-3',
    title: 'Projekt ustawy o ochronie zwierząt wykorzystywanych do celów naukowych',
    projectNumber: 'UD189',
    proposer: 'Minister Nauki i Szkolnictwa Wyższego',
    status: 'Prekonsultacje',
    startDate: '2025-12-05',
    endDate: '2025-12-25',
    description: 'Wzmocnienie standardów ochrony zwierząt laboratoryjnych oraz wprowadzenie obowiązku stosowania metod alternatywnych tam, gdzie jest to możliwe.',
    type: 'krajowe',
    tags: [
      { name: 'Ochrona zwierząt', variant: 'default' },
      { name: 'Nauka', variant: 'secondary' },
    ],
    popularity: 7200,
    documents: [
      { name: 'Projekt ustawy', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
      { name: 'OSR', type: 'OSR', url: '#' },
    ],
  },

  // KONSULTACJE REGIONALNE - NAJPOPULARNIEJSZE
  {
    id: 'reg-1',
    title: 'Studium uwarunkowań i kierunków zagospodarowania przestrzennego miasta Poznania',
    projectNumber: 'SUiKZP/2025/01',
    proposer: 'Prezydent Miasta Poznania',
    status: 'W trakcie konsultacji',
    startDate: '2025-11-20',
    endDate: '2025-12-20',
    description: 'Aktualizacja studium obejmująca rozwój terenów mieszkaniowych, przemysłowych oraz infrastruktury zielonej. Projekt uwzględnia zmiany demograficzne i potrzeby transportowe.',
    type: 'samorządowe',
    city: 'Poznań',
    region: 'Wielkopolska',
    institution: 'Urząd Miasta Poznania',
    institutionType: 'miasto na prawach powiatu',
    tags: [
      { name: 'Urbanistyka', variant: 'default' },
      { name: 'Planowanie przestrzenne', variant: 'secondary' },
    ],
    popularity: 6500,
    documents: [
      { name: 'Projekt studium', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
      { name: 'Mapa zmian', type: 'Inne', url: '#' },
    ],
  },
  {
    id: 'reg-2',
    title: 'Uchwała w sprawie Programu ochrony powietrza dla województwa wielkopolskiego',
    projectNumber: 'WOP/2025/12',
    proposer: 'Zarząd Województwa Wielkopolskiego',
    status: 'W trakcie konsultacji',
    startDate: '2025-12-01',
    endDate: '2025-12-31',
    description: 'Program mający na celu redukcję emisji pyłów PM10 i PM2.5 poprzez ograniczenie niskiej emisji, wymianę kotłów węglowych oraz rozwój transportu publicznego.',
    type: 'samorządowe',
    city: 'Poznań',
    region: 'Wielkopolska',
    institution: 'Urząd Marszałkowski Województwa Wielkopolskiego',
    institutionType: 'województwo',
    tags: [
      { name: 'Ekologia', variant: 'default' },
      { name: 'Ochrona powietrza', variant: 'secondary' },
    ],
    popularity: 5800,
    documents: [
      { name: 'Projekt programu', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
      { name: 'Analiza emisji', type: 'OSR', url: '#' },
    ],
  },
  {
    id: 'reg-3',
    title: 'Uchwała w sprawie regulaminu utrzymania czystości i porządku na terenie Gminy Luboń',
    projectNumber: 'GM/LUB/2025/05',
    proposer: 'Burmistrz Miasta Luboń',
    status: 'W trakcie konsultacji',
    startDate: '2025-11-28',
    endDate: '2025-12-18',
    description: 'Nowy regulamin określający zasady segregacji odpadów, częstotliwości wywozu śmieci oraz wysokości opłat za gospodarowanie odpadami komunalnymi.',
    type: 'samorządowe',
    city: 'Luboń',
    region: 'Wielkopolska',
    institution: 'Urząd Miasta Luboń',
    institutionType: 'gmina',
    tags: [
      { name: 'Gospodarka odpadami', variant: 'default' },
      { name: 'Opłaty lokalne', variant: 'secondary' },
    ],
    popularity: 4200,
    documents: [
      { name: 'Projekt regulaminu', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
    ],
  },

  // WIĘCEJ KONSULTACJI KRAJOWYCH
  {
    id: 'kraj-1',
    title: 'Projekt ustawy o zmianie ustawy o ochronie danych osobowych',
    projectNumber: 'UD221',
    proposer: 'Minister Cyfryzacji',
    status: 'W trakcie konsultacji',
    startDate: '2025-11-15',
    endDate: '2025-12-30',
    description: 'Dostosowanie przepisów krajowych do nowych wytycznych RODO oraz wprowadzenie uproszczeń dla małych przedsiębiorstw w zakresie ochrony danych.',
    type: 'krajowe',
    tags: [
      { name: 'RODO', variant: 'default' },
      { name: 'Ochrona danych', variant: 'secondary' },
      { name: 'Cyfryzacja', variant: 'outline' },
    ],
    popularity: 6800,
    documents: [
      { name: 'Projekt ustawy', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
      { name: 'OSR', type: 'OSR', url: '#' },
    ],
  },
  {
    id: 'kraj-2',
    title: 'Rozporządzenie w sprawie minimalnego wynagrodzenia za pracę w 2026 roku',
    projectNumber: 'RM/2025/158',
    proposer: 'Rada Ministrów',
    status: 'Opiniowanie',
    startDate: '2025-11-10',
    endDate: '2025-12-10',
    description: 'Podwyższenie minimalnego wynagrodzenia do 4666 zł brutto oraz minimalnej stawki godzinowej do 30,50 zł.',
    type: 'krajowe',
    tags: [
      { name: 'Płaca minimalna', variant: 'default' },
      { name: 'Wynagrodzenia', variant: 'secondary' },
    ],
    popularity: 9200,
    documents: [
      { name: 'Projekt rozporządzenia', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
      { name: 'OSR', type: 'OSR', url: '#' },
    ],
  },
  {
    id: 'kraj-3',
    title: 'Projekt ustawy o zmianie ustawy o elektromobilności',
    projectNumber: 'Druk nr 72',
    proposer: 'Komitet Inicjatywy Ustawodawczej',
    status: 'W trakcie konsultacji',
    startDate: '2025-12-03',
    endDate: '2025-12-23',
    description: 'Rozszerzenie ulg podatkowych dla pojazdów elektrycznych oraz zwiększenie dofinansowania do budowy stacji ładowania.',
    type: 'krajowe',
    tags: [
      { name: 'Transport', variant: 'default' },
      { name: 'Ekologia', variant: 'secondary' },
      { name: 'Elektromobilność', variant: 'outline' },
    ],
    popularity: 5400,
    documents: [
      { name: 'Projekt ustawy', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
    ],
  },

  // WIĘCEJ KONSULTACJI SAMORZĄDOWYCH
  {
    id: 'sam-1',
    title: 'Uchwała budżetowa Miasta Warszawy na rok 2026',
    projectNumber: 'WAW/BUD/2026',
    proposer: 'Prezydent Miasta Warszawy',
    status: 'W trakcie konsultacji',
    startDate: '2025-11-25',
    endDate: '2025-12-27',
    description: 'Projekt budżetu zakładający zwiększone wydatki na transport publiczny, edukację oraz inwestycje infrastrukturalne. Planowane dochody: 28,5 mld zł.',
    type: 'samorządowe',
    city: 'Warszawa',
    region: 'Mazowsze',
    institution: 'Urząd Miasta Warszawy',
    institutionType: 'miasto na prawach powiatu',
    tags: [
      { name: 'Budżet', variant: 'default' },
      { name: 'Finanse publiczne', variant: 'secondary' },
    ],
    popularity: 7800,
    documents: [
      { name: 'Projekt uchwały budżetowej', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
      { name: 'Załączniki budżetowe', type: 'Inne', url: '#' },
    ],
  },
  {
    id: 'sam-2',
    title: 'Plan gospodarki niskoemisyjnej dla Gminy Kórnik',
    projectNumber: 'GM/KOR/2025/18',
    proposer: 'Wójt Gminy Kórnik',
    status: 'W trakcie konsultacji',
    startDate: '2025-12-02',
    endDate: '2025-12-22',
    description: 'Plan mający na celu redukcję emisji CO2 o 20% do 2030 roku poprzez termomodernizację budynków publicznych i rozwój OZE.',
    type: 'samorządowe',
    city: 'Kórnik',
    region: 'Wielkopolska',
    institution: 'Urząd Gminy Kórnik',
    institutionType: 'gmina',
    tags: [
      { name: 'Klimat', variant: 'default' },
      { name: 'OZE', variant: 'secondary' },
    ],
    popularity: 3100,
    documents: [
      { name: 'Projekt planu', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
    ],
  },
  {
    id: 'sam-3',
    title: 'Miejscowy plan zagospodarowania przestrzennego - rejon ulic Grunwaldzkiej w Krakowie',
    projectNumber: 'KRK/MPZP/2025/44',
    proposer: 'Prezydent Miasta Krakowa',
    status: 'W trakcie konsultacji',
    startDate: '2025-11-18',
    endDate: '2025-12-18',
    description: 'Plan przewiduje przekształcenie terenów poprzemysłowych w obszar mieszkaniowo-usługowy z zachowaniem zieleni i terenów rekreacyjnych.',
    type: 'samorządowe',
    city: 'Kraków',
    region: 'Małopolska',
    institution: 'Urząd Miasta Krakowa',
    institutionType: 'miasto na prawach powiatu',
    tags: [
      { name: 'Planowanie przestrzenne', variant: 'default' },
      { name: 'Urbanistyka', variant: 'secondary' },
    ],
    popularity: 5600,
    documents: [
      { name: 'Projekt planu', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
      { name: 'Rysunek planu', type: 'Inne', url: '#' },
    ],
  },
  {
    id: 'sam-4',
    title: 'Uchwała w sprawie stawek podatku od nieruchomości w Gdańsku na rok 2026',
    projectNumber: 'GDA/POD/2026',
    proposer: 'Prezydent Miasta Gdańska',
    status: 'W trakcie konsultacji',
    startDate: '2025-12-01',
    endDate: '2025-12-21',
    description: 'Projekt zakłada waloryzację stawek podatku od nieruchomości zgodnie ze wskaźnikiem inflacji oraz wprowadzenie ulg dla inwestorów w OZE.',
    type: 'samorządowe',
    city: 'Gdańsk',
    region: 'Pomorze',
    institution: 'Urząd Miasta Gdańska',
    institutionType: 'miasto na prawach powiatu',
    tags: [
      { name: 'Podatki lokalne', variant: 'default' },
      { name: 'Finanse', variant: 'secondary' },
    ],
    popularity: 4800,
    documents: [
      { name: 'Projekt uchwały', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
    ],
  },
  {
    id: 'sam-5',
    title: 'Program współpracy Powiatu Poznańskiego z organizacjami pozarządowymi na 2026 rok',
    projectNumber: 'POZ/NGO/2026',
    proposer: 'Starosta Poznański',
    status: 'W trakcie konsultacji',
    startDate: '2025-11-22',
    endDate: '2025-12-15',
    description: 'Roczny program określający priorytety i zasady współpracy z NGO w obszarach: pomoc społeczna, kultura, sport, edukacja.',
    type: 'samorządowe',
    city: 'Poznań',
    region: 'Wielkopolska',
    institution: 'Starostwo Powiatowe w Poznaniu',
    institutionType: 'powiat',
    tags: [
      { name: 'NGO', variant: 'default' },
      { name: 'Współpraca', variant: 'secondary' },
    ],
    popularity: 2700,
    documents: [
      { name: 'Projekt programu', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
    ],
  },
  {
    id: 'sam-6',
    title: 'Strategia Rozwoju Województwa Dolnośląskiego 2030',
    projectNumber: 'DWOJ/STRAT/2030',
    proposer: 'Zarząd Województwa Dolnośląskiego',
    status: 'Opiniowanie',
    startDate: '2025-10-15',
    endDate: '2025-12-15',
    description: 'Długoterminowa strategia rozwoju regionu obejmująca gospodarkę, infrastrukturę, edukację i ochronę środowiska.',
    type: 'samorządowe',
    city: 'Wrocław',
    region: 'Dolny Śląsk',
    institution: 'Urząd Marszałkowski Województwa Dolnośląskiego',
    institutionType: 'województwo',
    tags: [
      { name: 'Strategia', variant: 'default' },
      { name: 'Rozwój regionalny', variant: 'secondary' },
    ],
    popularity: 6300,
    documents: [
      { name: 'Projekt strategii', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
      { name: 'Diagnozy', type: 'Inne', url: '#' },
    ],
  },
  
  // ADMINISTRACJA RZĄDOWA I INNE INSTYTUCJE
  {
    id: 'admin-1',
    title: 'Zarządzenie w sprawie regulaminu organizacyjnego Dolnośląskiego Urzędu Wojewódzkiego',
    projectNumber: 'DUW/WRO/2025/33',
    proposer: 'Dolnośląski Urząd Wojewódzki we Wrocławiu',
    status: 'W trakcie konsultacji',
    startDate: '2025-12-01',
    endDate: '2025-12-20',
    description: 'Aktualizacja struktury organizacyjnej urzędu w związku z nowymi zadaniami wynikającymi z przepisów prawa.',
    type: 'samorządowe',
    city: 'Wrocław',
    region: 'Dolny Śląsk',
    institution: 'Dolnośląski Urząd Wojewódzki we Wrocławiu',
    institutionType: 'Urząd Wojewódzki',
    tags: [
      { name: 'Organizacja', variant: 'default' },
      { name: 'Administracja', variant: 'secondary' },
    ],
    popularity: 2100,
    documents: [
      { name: 'Projekt zarządzenia', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
    ],
  },
  {
    id: 'admin-2',
    title: 'Program wychowawczo-profilaktyczny dla szkół w województwie wielkopolskim',
    projectNumber: 'KO/POZ/2025/18',
    proposer: 'Kuratorium Oświaty w Poznaniu',
    status: 'W trakcie konsultacji',
    startDate: '2025-11-28',
    endDate: '2025-12-22',
    description: 'Program mający na celu wsparcie szkół w realizacji zadań wychowawczych oraz działań profilaktycznych.',
    type: 'samorządowe',
    city: 'Poznań',
    region: 'Wielkopolska',
    institution: 'Kuratorium Oświaty w Poznaniu',
    institutionType: 'Kuratorium Oświaty',
    tags: [
      { name: 'Edukacja', variant: 'default' },
      { name: 'Wychowanie', variant: 'secondary' },
    ],
    popularity: 3400,
    documents: [
      { name: 'Projekt programu', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
    ],
  },
  {
    id: 'admin-3',
    title: 'Rozporządzenie w sprawie strefy ograniczonego użytkowania wokół składowiska odpadów',
    projectNumber: 'WSSE/WRO/2025/44',
    proposer: 'Wojewódzka Stacja Sanitarno-Epidemiologiczna we Wrocławiu',
    status: 'W trakcie konsultacji',
    startDate: '2025-12-03',
    endDate: '2025-12-28',
    description: 'Ustanowienie strefy ochronnej wokół składowiska odpadów komunalnych w celu ochrony zdrowia mieszkańców.',
    type: 'samorządowe',
    city: 'Wrocław',
    region: 'Dolny Śląsk',
    institution: 'Wojewódzka Stacja Sanitarno-Epidemiologiczna we Wrocławiu',
    institutionType: 'Inspektorat',
    tags: [
      { name: 'Zdrowie publiczne', variant: 'default' },
      { name: 'Ochrona środowiska', variant: 'secondary' },
    ],
    popularity: 2800,
    documents: [
      { name: 'Projekt rozporządzenia', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
    ],
  },
  {
    id: 'admin-4',
    title: 'Plan kontroli jakości handlowej artykułów rolno-spożywczych na 2026 rok',
    projectNumber: 'WIJH/WRO/2026/01',
    proposer: 'Wojewódzki Inspektorat Jakości Handlowej we Wrocławiu',
    status: 'Opiniowanie',
    startDate: '2025-11-15',
    endDate: '2025-12-10',
    description: 'Roczny plan kontroli produktów rolno-spożywczych pod kątem jakości handlowej i zgodności z przepisami.',
    type: 'samorządowe',
    city: 'Wrocław',
    region: 'Dolny Śląsk',
    institution: 'Wojewódzki Inspektorat Jakości Handlowej we Wrocławiu',
    institutionType: 'Inspektorat',
    tags: [
      { name: 'Kontrola jakości', variant: 'default' },
      { name: 'Handel', variant: 'secondary' },
    ],
    popularity: 1900,
    documents: [
      { name: 'Projekt planu', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
    ],
  },
  {
    id: 'admin-5',
    title: 'Uchwała w sprawie warunków technicznych dla obiektów budowlanych',
    projectNumber: 'WINB/WRO/2025/52',
    proposer: 'Wojewódzki Inspektorat Nadzoru Budowlanego we Wrocławiu',
    status: 'W trakcie konsultacji',
    startDate: '2025-12-01',
    endDate: '2025-12-25',
    description: 'Aktualizacja wymagań technicznych dla obiektów budowlanych w zakresie bezpieczeństwa i ochrony przeciwpożarowej.',
    type: 'samorządowe',
    city: 'Wrocław',
    region: 'Dolny Śląsk',
    institution: 'Wojewódzki Inspektorat Nadzoru Budowlanego we Wrocławiu',
    institutionType: 'Inspektorat',
    tags: [
      { name: 'Budownictwo', variant: 'default' },
      { name: 'Bezpieczeństwo', variant: 'secondary' },
    ],
    popularity: 4100,
    documents: [
      { name: 'Projekt uchwały', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
    ],
  },
  {
    id: 'admin-6',
    title: 'Program zwalczania afrykańskiego pomoru świń w województwie wielkopolskim',
    projectNumber: 'WIW/POZ/2025/29',
    proposer: 'Wojewódzki Inspektorat Weterynarii w Poznaniu',
    status: 'W trakcie konsultacji',
    startDate: '2025-11-25',
    endDate: '2025-12-18',
    description: 'Program mający na celu zapobieganie rozprzestrzenianiu się ASF oraz działania zwalczające w przypadku wystąpienia ognisk choroby.',
    type: 'samorządowe',
    city: 'Poznań',
    region: 'Wielkopolska',
    institution: 'Wojewódzki Inspektorat Weterynarii w Poznaniu',
    institutionType: 'Inspektorat',
    tags: [
      { name: 'Weterynaria', variant: 'default' },
      { name: 'Bezpieczeństwo żywności', variant: 'secondary' },
    ],
    popularity: 3200,
    documents: [
      { name: 'Projekt programu', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
    ],
  },
  {
    id: 'admin-7',
    title: 'Regulamin udzielania zamówień publicznych w Starostwie Powiatowym',
    projectNumber: 'SP/STR/2025/15',
    proposer: 'Starostwo Powiatowe w Strzelinie',
    status: 'W trakcie konsultacji',
    startDate: '2025-12-04',
    endDate: '2025-12-24',
    description: 'Wewnętrzny regulamin określający procedury udzielania zamówień publicznych zgodnie z nowymi przepisami ustawy Pzp.',
    type: 'samorządowe',
    city: 'Strzelin',
    region: 'Dolny Śląsk',
    institution: 'Starostwo Powiatowe w Strzelinie',
    institutionType: 'Starostwo Powiatowe',
    tags: [
      { name: 'Zamówienia publiczne', variant: 'default' },
      { name: 'Administracja', variant: 'secondary' },
    ],
    popularity: 1600,
    documents: [
      { name: 'Projekt regulaminu', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
    ],
  },
  {
    id: 'waw-parking-1',
    title: 'Jaka strefa płatnego parkowania we Włochach?',
    projectNumber: 'WAW/SPPN/2025/WL',
    proposer: 'Zarząd Dróg Miejskich w Warszawie',
    status: 'W trakcie konsultacji',
    startDate: '2025-11-12',
    endDate: '2025-12-31',
    description: 'Konsultacje społeczne dotyczące utworzenia Strefy Płatnego Parkowania Niestrzeżonego w dzielnicy Włochy. Drogi i transport / Włochy',
    type: 'samorządowe',
    city: 'Warszawa',
    region: 'Mazowsze',
    institution: 'Urząd Miasta Warszawy',
    institutionType: 'miasto na prawach powiatu',
    tags: [
      { name: 'Drogi i transport', variant: 'default' },
      { name: 'Włochy', variant: 'secondary' },
    ],
    popularity: 1250,
    documents: [
      { name: 'Konsultacje online', type: 'Inne', url: 'https://konsultacje.um.warszawa.pl/processes/sppn-wlochy2025' },
    ],
  },
  {
    id: 'waw-parking-2',
    title: 'Jaka strefa płatnego parkowania na Mokotowie? | 2025',
    projectNumber: 'WAW/SPPN/2025/MK',
    proposer: 'Zarząd Dróg Miejskich w Warszawie',
    status: 'W trakcie konsultacji',
    startDate: '2025-11-12',
    endDate: '2025-12-31',
    description: 'Konsultacje społeczne dotyczące rozszerzenia Strefy Płatnego Parkowania Niestrzeżonego w dzielnicy Mokotów. Drogi i transport / Mokotów',
    type: 'samorządowe',
    city: 'Warszawa',
    region: 'Mazowsze',
    institution: 'Urząd Miasta Warszawy',
    institutionType: 'miasto na prawach powiatu',
    tags: [
      { name: 'Drogi i transport', variant: 'default' },
      { name: 'Mokotów', variant: 'secondary' },
    ],
    popularity: 953,
    documents: [
      { name: 'Konsultacje online', type: 'Inne', url: 'https://konsultacje.um.warszawa.pl/processes/sppn-mokotow2025' },
    ],
  },
  {
    id: 'waw-mpzp-1',
    title: 'Jaki plan miejscowy dla Odolan – część I?',
    projectNumber: 'WAW/MPZP/2025/WOL',
    proposer: 'Biuro Architektury i Planowania Przestrzennego',
    status: 'W trakcie konsultacji',
    startDate: '2025-11-25',
    endDate: '2025-12-18',
    description: 'Konsultacje społeczne w sprawie sporządzenia miejscowego planu zagospodarowania przestrzennego dla rejonu Odolan w dzielnicy Wola. Plany miejscowe / Wola',
    type: 'samorządowe',
    city: 'Warszawa',
    region: 'Mazowsze',
    institution: 'Urząd Miasta Warszawy',
    institutionType: 'miasto na prawach powiatu',
    tags: [
      { name: 'Plany miejscowe', variant: 'default' },
      { name: 'Wola', variant: 'secondary' },
    ],
    popularity: 780,
    documents: [
      { name: 'Projekt planu', type: 'Projekt ustawy', url: '#' },
    ],
  },
  {
    id: 'waw-mpzp-2',
    title: 'Jaki plan miejscowy dla rejonu ulicy Strzeleckiej? | Wnioski',
    projectNumber: 'WAW/MPZP/2025/PRN',
    proposer: 'Biuro Architektury i Planowania Przestrzennego',
    status: 'Zakończone',
    startDate: '2025-10-15',
    endDate: '2025-12-04',
    description: 'Zakończone konsultacje dotyczące miejscowego planu zagospodarowania przestrzennego dla rejonu ulicy Strzeleckiej w dzielnicy Praga-Północ. Plany miejscowe / Praga-Północ',
    type: 'samorządowe',
    city: 'Warszawa',
    region: 'Mazowsze',
    institution: 'Urząd Miasta Warszawy',
    institutionType: 'miasto na prawach powiatu',
    tags: [
      { name: 'Plany miejscowe', variant: 'default' },
      { name: 'Praga-Północ', variant: 'secondary' },
    ],
    popularity: 620,
    documents: [
      { name: 'Projekt planu', type: 'Projekt ustawy', url: '#' },
      { name: 'Wnioski mieszkańców', type: 'Inne', url: '#' },
    ],
  },
  {
    id: 'waw-space-1',
    title: 'Jaka ulica Wileńska?',
    projectNumber: 'WAW/SPACE/2025/PRN',
    proposer: 'Zarząd Dróg Miejskich w Warszawie',
    status: 'Zakończone',
    startDate: '2025-09-20',
    endDate: '2025-11-30',
    description: 'Zakończone konsultacje społeczne dotyczące przebudowy ulicy Wileńskiej w dzielnicy Praga-Północ. Przestrzeń publiczna / Praga-Północ',
    type: 'samorządowe',
    city: 'Warszawa',
    region: 'Mazowsze',
    institution: 'Urząd Miasta Warszawy',
    institutionType: 'miasto na prawach powiatu',
    tags: [
      { name: 'Przestrzeń publiczna', variant: 'default' },
      { name: 'Praga-Północ', variant: 'secondary' },
    ],
    popularity: 1580,
    documents: [
      { name: 'Projekt przebudowy', type: 'Projekt ustawy', url: '#' },
      { name: 'Wyniki konsultacji', type: 'Inne', url: '#' },
    ],
  },
  {
    id: 'admin-8',
    title: 'Program ochrony zdrowia psychicznego dla dzieci i młodzieży',
    projectNumber: 'MUW/WAW/2025/67',
    proposer: 'Mazowiecki Urząd Wojewódzki w Warszawie',
    status: 'W trakcie konsultacji',
    startDate: '2025-11-20',
    endDate: '2025-12-20',
    description: 'Kompleksowy program wsparcia zdrowia psychicznego dzieci i młodzieży obejmujący profilaktykę i terapię.',
    type: 'samorządowe',
    city: 'Warszawa',
    region: 'Mazowsze',
    institution: 'Mazowiecki Urząd Wojewódzki w Warszawie',
    institutionType: 'Urząd Wojewódzki',
    tags: [
      { name: 'Zdrowie', variant: 'default' },
      { name: 'Młodzież', variant: 'secondary' },
    ],
    popularity: 5200,
    documents: [
      { name: 'Projekt programu', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
    ],
  },
  {
    id: 'admin-9',
    title: 'Uchwała w sprawie sieci szkół ponadpodstawowych w Krakowie',
    projectNumber: 'KO/KRK/2025/41',
    proposer: 'Kuratorium Oświaty w Krakowie',
    status: 'W trakcie konsultacji',
    startDate: '2025-12-02',
    endDate: '2025-12-23',
    description: 'Plan reorganizacji sieci szkół ponadpodstawowych w związku z niżem demograficznym i zmianami w systemie edukacji.',
    type: 'samorządowe',
    city: 'Kraków',
    region: 'Małopolska',
    institution: 'Kuratorium Oświaty w Krakowie',
    institutionType: 'Kuratorium Oświaty',
    tags: [
      { name: 'Edukacja', variant: 'default' },
      { name: 'Szkolnictwo', variant: 'secondary' },
    ],
    popularity: 4600,
    documents: [
      { name: 'Projekt uchwały', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
    ],
  },
  {
    id: 'admin-10',
    title: 'Program ochrony środowiska dla województwa śląskiego na lata 2026-2030',
    projectNumber: 'SUW/KAT/2026/12',
    proposer: 'Śląski Urząd Wojewódzki w Katowicach',
    status: 'W trakcie konsultacji',
    startDate: '2025-11-18',
    endDate: '2025-12-30',
    description: 'Długoterminowy program działań na rzecz poprawy stanu środowiska naturalnego, ze szczególnym uwzględnieniem jakości powietrza.',
    type: 'samorządowe',
    city: 'Katowice',
    region: 'Śląsk',
    institution: 'Śląski Urząd Wojewódzki w Katowicach',
    institutionType: 'Urząd Wojewódzki',
    tags: [
      { name: 'Środowisko', variant: 'default' },
      { name: 'Jakość powietrza', variant: 'secondary' },
    ],
    popularity: 6700,
    documents: [
      { name: 'Projekt programu', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
      { name: 'Diagnozy', type: 'Inne', url: '#' },
    ],
  },
  {
    id: 'sam-7',
    title: 'Uchwała w sprawie strefy płatnego parkowania w centrum Łodzi',
    projectNumber: 'LOD/SPP/2025/28',
    proposer: 'Prezydent Miasta Łodzi',
    status: 'W trakcie konsultacji',
    startDate: '2025-11-30',
    endDate: '2025-12-30',
    description: 'Rozszerzenie strefy płatnego parkowania oraz podwyższenie stawek opłat w centrum miasta.',
    type: 'samorządowe',
    city: 'Łódź',
    region: 'Łódzkie',
    institution: 'Urząd Miasta Łodzi',
    institutionType: 'miasto na prawach powiatu',
    tags: [
      { name: 'Transport', variant: 'default' },
      { name: 'Parkowanie', variant: 'secondary' },
    ],
    popularity: 5100,
    documents: [
      { name: 'Projekt uchwały', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
    ],
  },
  {
    id: 'sam-8',
    title: 'Miejscowy plan zagospodarowania przestrzennego - rejon Starego Miasta w Gdańsku',
    projectNumber: 'GDA/MPZP/2025/67',
    proposer: 'Prezydent Miasta Gdańska',
    status: 'W trakcie konsultacji',
    startDate: '2025-11-22',
    endDate: '2025-12-22',
    description: 'Plan ochrony historycznego centrum Gdańska z zachowaniem zabytkowego charakteru zabudowy.',
    type: 'samorządowe',
    city: 'Gdańsk',
    region: 'Pomorze',
    institution: 'Urząd Miasta Gdańska',
    institutionType: 'miasto na prawach powiatu',
    tags: [
      { name: 'Zabytki', variant: 'default' },
      { name: 'Planowanie przestrzenne', variant: 'secondary' },
    ],
    popularity: 4300,
    documents: [
      { name: 'Projekt planu', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
      { name: 'Rysunek planu', type: 'Inne', url: '#' },
    ],
  },
  {
    id: 'sam-9',
    title: 'Program rozwoju elektromobilności dla Miasta Szczecin',
    projectNumber: 'SZC/ELEK/2025/19',
    proposer: 'Prezydent Miasta Szczecin',
    status: 'Opiniowanie',
    startDate: '2025-11-10',
    endDate: '2025-12-15',
    description: 'Program zakładający budowę infrastruktury ładowania pojazdów elektrycznych oraz wymianę floty autobusów miejskich.',
    type: 'samorządowe',
    city: 'Szczecin',
    region: 'Zachodniopomorskie',
    institution: 'Urząd Miasta Szczecin',
    institutionType: 'miasto na prawach powiatu',
    tags: [
      { name: 'Transport', variant: 'default' },
      { name: 'Elektromobilność', variant: 'secondary' },
    ],
    popularity: 3900,
    documents: [
      { name: 'Projekt programu', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
    ],
  },
  {
    id: 'sam-10',
    title: 'Strategia rozwoju turystyki w Gminie Zakopane do 2030 roku',
    projectNumber: 'ZAK/TUR/2030',
    proposer: 'Burmistrz Zakopanego',
    status: 'W trakcie konsultacji',
    startDate: '2025-11-25',
    endDate: '2025-12-25',
    description: 'Strategia zrównoważonego rozwoju turystyki z uwzględnieniem ochrony środowiska naturalnego i dziedzictwa kulturowego.',
    type: 'samorządowe',
    city: 'Zakopane',
    region: 'Małopolska',
    institution: 'Urząd Miasta Zakopane',
    institutionType: 'gmina',
    tags: [
      { name: 'Turystyka', variant: 'default' },
      { name: 'Rozwój lokalny', variant: 'secondary' },
    ],
    popularity: 3600,
    documents: [
      { name: 'Projekt strategii', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
    ],
  },
  {
    id: 'admin-11',
    title: 'Zarządzenie w sprawie standardów weterynaryjnych dla schronisk dla zwierząt',
    projectNumber: 'WIW/GDA/2025/34',
    proposer: 'Wojewódzki Inspektorat Weterynarii w Gdańsku',
    status: 'W trakcie konsultacji',
    startDate: '2025-12-01',
    endDate: '2025-12-21',
    description: 'Określenie minimalnych standardów utrzymania zwierząt w schroniskach oraz wymagań dla personelu.',
    type: 'samorządowe',
    city: 'Gdańsk',
    region: 'Pomorze',
    institution: 'Wojewódzki Inspektorat Weterynarii w Gdańsku',
    institutionType: 'Inspektorat',
    tags: [
      { name: 'Ochrona zwierząt', variant: 'default' },
      { name: 'Weterynaria', variant: 'secondary' },
    ],
    popularity: 2900,
    documents: [
      { name: 'Projekt zarządzenia', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
    ],
  },
  {
    id: 'admin-12',
    title: 'Program modernizacji oczyszczalni ścieków w powiecie poznańskim',
    projectNumber: 'SP/POZ/2025/44',
    proposer: 'Starostwo Powiatowe w Poznaniu',
    status: 'W trakcie konsultacji',
    startDate: '2025-11-28',
    endDate: '2025-12-28',
    description: 'Wieloletni program inwestycyjny mający na celu poprawę jakości oczyszczania ścieków komunalnych.',
    type: 'samorządowe',
    city: 'Poznań',
    region: 'Wielkopolska',
    institution: 'Starostwo Powiatowe w Poznaniu',
    institutionType: 'Starostwo Powiatowe',
    tags: [
      { name: 'Infrastruktura', variant: 'default' },
      { name: 'Gospodarka wodna', variant: 'secondary' },
    ],
    popularity: 2400,
    documents: [
      { name: 'Projekt programu', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
      { name: 'Kosztorys', type: 'OSR', url: '#' },
    ],
  },
  {
    id: 'kraj-4',
    title: 'Projekt ustawy o zmianie ustawy o podatku od towarów i usług',
    projectNumber: 'UD245',
    proposer: 'Minister Finansów',
    status: 'W trakcie konsultacji',
    startDate: '2025-12-01',
    endDate: '2025-12-29',
    description: 'Implementacja dyrektyw unijnych dotyczących VAT oraz zmiany w zakresie stawek preferencyjnych dla wybranych towarów i usług.',
    type: 'krajowe',
    tags: [
      { name: 'Podatki', variant: 'default' },
      { name: 'VAT', variant: 'secondary' },
      { name: 'Finanse', variant: 'outline' },
    ],
    popularity: 8900,
    documents: [
      { name: 'Projekt ustawy', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
      { name: 'OSR', type: 'OSR', url: '#' },
    ],
  },
  {
    id: 'kraj-5',
    title: 'Projekt ustawy o gospodarce o obiegu zamkniętym',
    projectNumber: 'UD198',
    proposer: 'Minister Klimatu i Środowiska',
    status: 'Prekonsultacje',
    startDate: '2025-11-20',
    endDate: '2025-12-20',
    description: 'Wprowadzenie mechanizmów wspierających recykling i ograniczenie wytwarzania odpadów zgodnie z zasadami gospodarki cyrkularnej.',
    type: 'krajowe',
    tags: [
      { name: 'Środowisko', variant: 'default' },
      { name: 'Recykling', variant: 'secondary' },
      { name: 'GOZ', variant: 'outline' },
    ],
    popularity: 6100,
    documents: [
      { name: 'Projekt ustawy', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
    ],
  },
  {
    id: 'kraj-6',
    title: 'Rozporządzenie w sprawie kwalifikacji nauczycieli przedmiotów zawodowych',
    projectNumber: 'RM/2025/189',
    proposer: 'Minister Edukacji Narodowej',
    status: 'Opiniowanie',
    startDate: '2025-11-15',
    endDate: '2025-12-14',
    description: 'Aktualizacja wymagań kwalifikacyjnych dla nauczycieli przedmiotów zawodowych w szkołach branżowych.',
    type: 'krajowe',
    tags: [
      { name: 'Edukacja', variant: 'default' },
      { name: 'Kwalifikacje', variant: 'secondary' },
    ],
    popularity: 4400,
    documents: [
      { name: 'Projekt rozporządzenia', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
    ],
  },
  {
    id: 'sam-11',
    title: 'Uchwała w sprawie programu opieki nad zwierzętami bezdomnymi w Lublinie',
    projectNumber: 'LUB/ZWIERZ/2026',
    proposer: 'Prezydent Miasta Lublin',
    status: 'W trakcie konsultacji',
    startDate: '2025-11-26',
    endDate: '2025-12-26',
    description: 'Roczny program określający zadania gminy w zakresie opieki nad zwierzętami bezdomnymi oraz zapobiegania bezdomności.',
    type: 'samorządowe',
    city: 'Lublin',
    region: 'Lubelskie',
    institution: 'Urząd Miasta Lublin',
    institutionType: 'miasto na prawach powiatu',
    tags: [
      { name: 'Ochrona zwierząt', variant: 'default' },
      { name: 'Dobro zwierząt', variant: 'secondary' },
    ],
    popularity: 3700,
    documents: [
      { name: 'Projekt programu', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
    ],
  },
  {
    id: 'sam-12',
    title: 'Plan adaptacji do zmian klimatu dla miasta Białystok',
    projectNumber: 'BIA/KLIM/2025/31',
    proposer: 'Prezydent Miasta Białystok',
    status: 'W trakcie konsultacji',
    startDate: '2025-12-03',
    endDate: '2025-12-31',
    description: 'Plan działań adaptacyjnych do zmian klimatu obejmujący zarządzanie wodami opadowymi, ochronę przed upałami i zwiększenie powierzchni zieleni.',
    type: 'samorządowe',
    city: 'Białystok',
    region: 'Podlaskie',
    institution: 'Urząd Miasta Białystok',
    institutionType: 'miasto na prawach powiatu',
    tags: [
      { name: 'Klimat', variant: 'default' },
      { name: 'Adaptacja', variant: 'secondary' },
    ],
    popularity: 3200,
    documents: [
      { name: 'Projekt planu', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
    ],
  },
  {
    id: 'admin-13',
    title: 'Wytyczne w sprawie bezpieczeństwa obiektów użyteczności publicznej',
    projectNumber: 'WINB/LOD/2025/58',
    proposer: 'Wojewódzki Inspektorat Nadzoru Budowlanego w Łodzi',
    status: 'W trakcie konsultacji',
    startDate: '2025-11-29',
    endDate: '2025-12-29',
    description: 'Wytyczne dotyczące kontroli technicznej obiektów użyteczności publicznej pod kątem bezpieczeństwa użytkowników.',
    type: 'samorządowe',
    city: 'Łódź',
    region: 'Łódzkie',
    institution: 'Wojewódzki Inspektorat Nadzoru Budowlanego w Łodzi',
    institutionType: 'Inspektorat',
    tags: [
      { name: 'Bezpieczeństwo', variant: 'default' },
      { name: 'Budownictwo', variant: 'secondary' },
    ],
    popularity: 2600,
    documents: [
      { name: 'Projekt wytycznych', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
    ],
  },
  
  // ZAKOŃCZONE KONSULTACJE
  {
    id: 'zakoncz-1',
    title: 'Uchwała w sprawie stawek opłat za gospodarowanie odpadami komunalnymi w 2025 roku',
    projectNumber: 'POZ/ODP/2025/01',
    proposer: 'Prezydent Miasta Poznania',
    status: 'Zakończone',
    startDate: '2025-09-01',
    endDate: '2025-10-15',
    description: 'Ustalenie stawek opłat za odbiór i zagospodarowanie odpadów komunalnych na rok 2025. Konsultacje zakończone.',
    type: 'samorządowe',
    city: 'Poznań',
    region: 'Wielkopolska',
    institution: 'Urząd Miasta Poznania',
    institutionType: 'miasto na prawach powiatu',
    tags: [
      { name: 'Gospodarka odpadami', variant: 'default' },
      { name: 'Opłaty', variant: 'secondary' },
    ],
    popularity: 6800,
    documents: [
      { name: 'Projekt uchwały', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
    ],
  },
  {
    id: 'zakoncz-2',
    title: 'Projekt ustawy o zmianie ustawy o cenach energii elektrycznej',
    projectNumber: 'UD178',
    proposer: 'Minister Klimatu i Środowiska',
    status: 'Zakończone',
    startDate: '2025-08-15',
    endDate: '2025-09-30',
    description: 'Zmiana przepisów dotyczących maksymalnych cen energii elektrycznej dla gospodarstw domowych. Proces konsultacyjny zakończony.',
    type: 'krajowe',
    tags: [
      { name: 'Energia', variant: 'default' },
      { name: 'Ceny', variant: 'secondary' },
    ],
    popularity: 12400,
    documents: [
      { name: 'Projekt ustawy', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
      { name: 'OSR', type: 'OSR', url: '#' },
    ],
  },
  {
    id: 'zakoncz-3',
    title: 'Regulamin korzystania z basenu miejskiego w Gdańsku',
    projectNumber: 'GDA/SPORT/2025/12',
    proposer: 'Prezydent Miasta Gdańska',
    status: 'Zakończone',
    startDate: '2025-09-10',
    endDate: '2025-10-10',
    description: 'Nowy regulamin korzystania z obiektów sportowych - basenu miejskiego. Konsultacje społeczne zakończone.',
    type: 'samorządowe',
    city: 'Gdańsk',
    region: 'Pomorze',
    institution: 'Urząd Miasta Gdańska',
    institutionType: 'miasto na prawach powiatu',
    tags: [
      { name: 'Sport', variant: 'default' },
      { name: 'Rekreacja', variant: 'secondary' },
    ],
    popularity: 3100,
    documents: [
      { name: 'Projekt regulaminu', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
    ],
  },
  
  // KONSULTACJE BYDGOSZCZ
  {
    id: 'byd-1',
    title: 'Bydgoski Budżet Obywatelski – regulamin programu',
    projectNumber: 'BYD/BBO/2025/08',
    proposer: 'Prezydent Miasta Bydgoszczy',
    status: 'W trakcie konsultacji',
    startDate: '2025-11-15',
    endDate: '2025-12-31',
    description: 'Rozpoczynamy konsultacje społeczne regulaminu programu Bydgoski Budżet Obywatelski. Twoje zdanie ma znaczenie!',
    type: 'samorządowe',
    city: 'Bydgoszcz',
    region: 'Kujawsko-Pomorskie',
    institution: 'Urząd Miasta Bydgoszczy',
    institutionType: 'miasto na prawach powiatu',
    tags: [
      { name: 'Budżet obywatelski', variant: 'default' },
      { name: 'Partycypacja', variant: 'secondary' },
    ],
    popularity: 8900,
    documents: [
      { name: 'Projekt regulaminu', type: 'Projekt ustawy', url: 'https://www.bydgoskiekonsultacje.pl/2025/03/bydgoski-budzet-obywatelski-twoje.html' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
    ],
  },
  {
    id: 'byd-2',
    title: 'Konsultacje społeczne dotyczące zdrowia psychicznego mieszkańców',
    projectNumber: 'BYD/ZDROW/2025/14',
    proposer: 'Prezydent Miasta Bydgoszczy',
    status: 'W trakcie konsultacji',
    startDate: '2025-10-01',
    endDate: '2025-12-15',
    description: 'Miasto Bydgoszcz zaprasza mieszkańców do udziału w konsultacjach społecznych dotyczących programu wsparcia zdrowia psychicznego.',
    type: 'samorządowe',
    city: 'Bydgoszcz',
    region: 'Kujawsko-Pomorskie',
    institution: 'Urząd Miasta Bydgoszczy',
    institutionType: 'miasto na prawach powiatu',
    tags: [
      { name: 'Zdrowie', variant: 'default' },
      { name: 'Zdrowie psychiczne', variant: 'secondary' },
    ],
    popularity: 7200,
    documents: [
      { name: 'Projekt programu', type: 'Projekt ustawy', url: 'https://www.bydgoskiekonsultacje.pl/2025/09/bydgoszcz-pyta-mieszkancow-o-zdrowie.html' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
    ],
  },
  {
    id: 'byd-3',
    title: 'Konsultacje dotyczące wykorzystania autobusów zeroemisyjnych',
    projectNumber: 'BYD/TRANS/2025/22',
    proposer: 'Prezydent Miasta Bydgoszczy',
    status: 'W trakcie konsultacji',
    startDate: '2025-09-19',
    endDate: '2025-12-10',
    description: 'Konsultacje społeczne dotyczące rozbudowy floty autobusów zeroemisyjnych w komunikacji miejskiej oraz tras ich kursowania.',
    type: 'samorządowe',
    city: 'Bydgoszcz',
    region: 'Kujawsko-Pomorskie',
    institution: 'Urząd Miasta Bydgoszczy',
    institutionType: 'miasto na prawach powiatu',
    tags: [
      { name: 'Transport', variant: 'default' },
      { name: 'Ekologia', variant: 'secondary' },
    ],
    popularity: 6800,
    documents: [
      { name: 'Projekt uchwały', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
    ],
  },
  {
    id: 'byd-4',
    title: 'Miejscowy plan zagospodarowania przestrzennego „Bartodzieje–Cegielniana"',
    projectNumber: 'BYD/MPZP/2025/33',
    proposer: 'Prezydent Miasta Bydgoszczy',
    status: 'W trakcie konsultacji',
    startDate: '2025-08-10',
    endDate: '2025-12-20',
    description: 'Prezydent Miasta Bydgoszczy zaprasza mieszkańców do udziału w konsultacjach społecznych dotyczących projektu miejscowego planu zagospodarowania przestrzennego dla rejonu Bartodzieje-Cegielniana.',
    type: 'samorządowe',
    city: 'Bydgoszcz',
    region: 'Kujawsko-Pomorskie',
    institution: 'Urząd Miasta Bydgoszczy',
    institutionType: 'miasto na prawach powiatu',
    tags: [
      { name: 'Planowanie przestrzenne', variant: 'default' },
      { name: 'Urbanistyka', variant: 'secondary' },
    ],
    popularity: 5400,
    documents: [
      { name: 'Projekt planu', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
      { name: 'Rysunek planu', type: 'Inne', url: '#' },
    ],
  },
  {
    id: 'byd-5',
    title: 'Badanie dotyczące komunikacji mieszkańców z samorządem lokalnym',
    projectNumber: 'BYD/KOM/2025/17',
    proposer: 'Prezydent Miasta Bydgoszczy',
    status: 'W trakcie konsultacji',
    startDate: '2025-09-01',
    endDate: '2025-12-12',
    description: 'Zachęcamy wszystkich mieszkańców Bydgoszczy do wzięcia udziału w badaniu dotyczącym form i jakości komunikacji z urzędem miasta.',
    type: 'samorządowe',
    city: 'Bydgoszcz',
    region: 'Kujawsko-Pomorskie',
    institution: 'Urząd Miasta Bydgoszczy',
    institutionType: 'miasto na prawach powiatu',
    tags: [
      { name: 'Komunikacja', variant: 'default' },
      { name: 'E-administracja', variant: 'secondary' },
    ],
    popularity: 4100,
    documents: [
      { name: 'Ankieta', type: 'Inne', url: 'https://www.bydgoskiekonsultacje.pl/2025/09/zaproszenie-do-udziau-w-badaniu.html' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
    ],
  },
  {
    id: 'byd-6',
    title: 'Plan "Łęgnowo - bocznice" - publiczny wgląd',
    projectNumber: 'BYD/MPZP/2025/45',
    proposer: 'Prezydent Miasta Bydgoszczy',
    status: 'W trakcie konsultacji',
    startDate: '2025-08-15',
    endDate: '2025-12-18',
    description: 'Zawiadamiamy o wyłożeniu do publicznego wglądu projektu miejscowego planu zagospodarowania przestrzennego dla rejonu Łęgnowo-bocznice.',
    type: 'samorządowe',
    city: 'Bydgoszcz',
    region: 'Kujawsko-Pomorskie',
    institution: 'Urząd Miasta Bydgoszczy',
    institutionType: 'miasto na prawach powiatu',
    tags: [
      { name: 'Planowanie przestrzenne', variant: 'default' },
      { name: 'Infrastruktura', variant: 'secondary' },
    ],
    popularity: 3800,
    documents: [
      { name: 'Projekt planu', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
    ],
  },
  {
    id: 'byd-7',
    title: 'Konsultacje Stowarzyszenia Metropolia Bydgoszcz',
    projectNumber: 'MB/STRAT/2025/09',
    proposer: 'Stowarzyszenie Metropolia Bydgoszcz',
    status: 'W trakcie konsultacji',
    startDate: '2025-08-20',
    endDate: '2025-12-15',
    description: 'Stowarzyszenie Metropolia Bydgoszcz zaprasza do udziału w konsultacjach społecznych dotyczących strategii rozwoju aglomeracji bydgoskiej.',
    type: 'samorządowe',
    city: 'Bydgoszcz',
    region: 'Kujawsko-Pomorskie',
    institution: 'Stowarzyszenie Metropolia Bydgoszcz',
    institutionType: 'Inne instytucje publiczne',
    tags: [
      { name: 'Rozwój regionalny', variant: 'default' },
      { name: 'Strategia', variant: 'secondary' },
    ],
    popularity: 2900,
    documents: [
      { name: 'Projekt strategii', type: 'Projekt ustawy', url: '#' },
      { name: 'Uzasadnienie', type: 'Uzasadnienie', url: '#' },
    ],
  },
];
