export const lawsData = [
  {
    id: '1',
    name: 'Ustawa o przeciwdziałaniu pornografii dziecięcej',
    lastUpdate: '19-08-2024',
    category: 'ustawy',
    tags: [
      { name: 'Bezpieczeństwo', variant: 'secondary' },
      { name: 'Dzieci', variant: 'outline' },
    ],
    stage: 'Etap 2',
  },
  {
    id: '2',
    name: 'Ustawa o ochronie danych osobowych',
    lastUpdate: '15-07-2024',
    category: 'ustawy',
    tags: [
      { name: 'Bezpieczeństwo', variant: 'destructive' },
      { name: 'Prywatność', variant: 'default' },
    ],
    stage: 'Etap 1',
  },
  {
    id: '3',
    name: 'Ustawa o edukacji',
    lastUpdate: '20-06-2024',
    category: 'ustawy',
    tags: [
      { name: 'Edukacja', variant: 'secondary' },
    ],
    stage: 'Etap 3',
  },
  {
    id: '4',
    name: 'Ustawa o ochronie konsumentów',
    lastUpdate: '12-05-2024',
    category: 'ustawy',
    tags: [
      { name: 'Ochrona', variant: 'secondary' },
      { name: 'Handel', variant: 'outline' },
    ],
    stage: 'Etap 2',
  },
  {
    id: '5',
    name: 'Ustawa o zdrowiu publicznym',
    lastUpdate: '08-04-2024',
    category: 'ustawy',
    tags: [
      { name: 'Zdrowie', variant: 'destructive' },
      { name: 'Medycyna', variant: 'default' },
    ],
    stage: 'Etap 1',
  },
  {
    id: '6',
    name: 'Ustawa o bezpieczeństwie alimentarnym',
    lastUpdate: '03-03-2024',
    category: 'ustawy',
    tags: [
      { name: 'Zdrowie', variant: 'secondary' },
      { name: 'Ochrona', variant: 'outline' },
    ],
    stage: 'Etap 3',
  },
  {
    id: '7',
    name: 'Ustawa o ochronie środowiska',
    lastUpdate: '25-02-2024',
    category: 'ustawy',
    tags: [
      { name: 'Ekologia', variant: 'secondary' },
      { name: 'Ochrona', variant: 'outline' },
    ],
    stage: 'Etap 2',
  },
  {
    id: '8',
    name: 'Ustawa o regulacji transportu',
    lastUpdate: '18-01-2024',
    category: 'ustawy',
    tags: [
      { name: 'Transport', variant: 'default' },
      { name: 'Infrastruktura', variant: 'secondary' },
    ],
    stage: 'Etap 1',
  },
  {
    id: '9',
    name: 'Ustawa o świadczeniach rodzinnych',
    lastUpdate: '10-12-2023',
    category: 'ustawy',
    tags: [
      { name: 'Socjalne', variant: 'secondary' },
      { name: 'Rodzina', variant: 'outline' },
    ],
    stage: 'Etap 3',
  },
  {
    id: '10',
    name: 'Ustawa o zatrudnieniu i pracy',
    lastUpdate: '05-11-2023',
    category: 'ustawy',
    tags: [
      { name: 'Praca', variant: 'destructive' },
      { name: 'Socjalne', variant: 'default' },
    ],
    stage: 'Etap 2',
  },
  {
    id: '11',
    name: 'Rozporządzenie o standardach bezpieczeństwa',
    lastUpdate: '28-10-2023',
    category: 'rozporzadzenia',
    tags: [
      { name: 'Bezpieczeństwo', variant: 'secondary' },
      { name: 'Prawo', variant: 'outline' },
    ],
    stage: 'Etap 1',
  },
  {
    id: '12',
    name: 'Rozporządzenie o procedurach administracyjnych',
    lastUpdate: '15-09-2023',
    category: 'rozporzadzenia',
    tags: [
      { name: 'Finanse', variant: 'default' },
      { name: 'Budżet', variant: 'secondary' },
    ],
    stage: 'Etap 3',
  },
  {
    id: '13',
    name: 'Rozporządzenie w sprawie podatków',
    lastUpdate: '08-08-2023',
    category: 'rozporzadzenia',
    tags: [
      { name: 'Finanse', variant: 'destructive' },
      { name: 'Podatki', variant: 'secondary' },
    ],
    stage: 'Etap 2',
  },
  {
    id: '14',
    name: 'Rozporządzenie o handlu zagranicznym',
    lastUpdate: '01-07-2023',
    category: 'rozporzadzenia',
    tags: [
      { name: 'Podatki', variant: 'secondary' },
      { name: 'Handel', variant: 'outline' },
    ],
    stage: 'Etap 1',
  },
  {
    id: '15',
    name: 'Rozporządzenie o ochronie konsumenta',
    lastUpdate: '20-06-2023',
    category: 'rozporzadzenia',
    tags: [
      { name: 'Prawo', variant: 'default' },
      { name: 'Ochrona', variant: 'secondary' },
    ],
    stage: 'Etap 3',
  },
  {
    id: '16',
    name: 'Rozporządzenie o górnictwie',
    lastUpdate: '12-05-2023',
    category: 'rozporzadzenia',
    tags: [
      { name: 'Surowce', variant: 'secondary' },
      { name: 'Infrastruktura', variant: 'outline' },
    ],
    stage: 'Etap 2',
  },
  {
    id: '17',
    name: 'Rozporządzenie o energetyce',
    lastUpdate: '05-04-2023',
    category: 'rozporzadzenia',
    tags: [
      { name: 'Infrastruktura', variant: 'destructive' },
      { name: 'Surowce', variant: 'secondary' },
    ],
    stage: 'Etap 1',
  },
  {
    id: '18',
    name: 'Rozporządzenie o telekomunikacji',
    lastUpdate: '28-03-2023',
    category: 'rozporzadzenia',
    tags: [
      { name: 'Technologia', variant: 'secondary' },
      { name: 'Transport', variant: 'outline' },
    ],
    stage: 'Etap 3',
  },
  {
    id: '19',
    name: 'Rozporządzenie o handlu elektronicznym',
    lastUpdate: '15-02-2023',
    category: 'rozporzadzenia',
    tags: [
      { name: 'Handel', variant: 'default' },
      { name: 'Technologia', variant: 'secondary' },
    ],
    stage: 'Etap 2',
  },
  {
    id: '20',
    name: 'Rozporządzenie o ochronie danych',
    lastUpdate: '08-01-2023',
    category: 'rozporzadzenia',
    tags: [
      { name: 'Prawo', variant: 'secondary' },
      { name: 'Bezpieczeństwo', variant: 'outline' },
    ],
    stage: 'Etap 1',
  },
  {
    id: '21',
    name: 'Zarządzenie w sprawie organizacji pracy',
    lastUpdate: '22-12-2022',
    category: 'inne',
    tags: [
      { name: 'Organizacja', variant: 'destructive' },
      { name: 'Praca', variant: 'secondary' },
    ],
    stage: 'Etap 3',
  },
  {
    id: '22',
    name: 'Obwieszczenie o zmianach przepisów',
    lastUpdate: '15-11-2022',
    category: 'inne',
    tags: [
      { name: 'Innowacje', variant: 'secondary' },
      { name: 'Prawo', variant: 'outline' },
    ],
    stage: 'Etap 2',
  },
  {
    id: '23',
    name: 'Zarządzenie o procedurach',
    lastUpdate: '08-10-2022',
    category: 'inne',
    tags: [
      { name: 'Handel', variant: 'default' },
      { name: 'Eksport', variant: 'secondary' },
    ],
    stage: 'Etap 1',
  },
  {
    id: '24',
    name: 'Obwieszczenie o nowelizacji',
    lastUpdate: '01-09-2022',
    category: 'inne',
    tags: [
      { name: 'Cła', variant: 'secondary' },
      { name: 'Handel', variant: 'outline' },
    ],
    stage: 'Etap 3',
  },
  {
    id: '25',
    name: 'Zarządzenie o ochronie',
    lastUpdate: '20-08-2022',
    category: 'inne',
    tags: [
      { name: 'Ochrona', variant: 'destructive' },
      { name: 'Bezpieczeństwo', variant: 'secondary' },
    ],
    stage: 'Etap 2',
  },
  {
    id: '26',
    name: 'Obwieszczenie o konkurencji',
    lastUpdate: '12-07-2022',
    category: 'inne',
    tags: [
      { name: 'Konkurencja', variant: 'secondary' },
      { name: 'Rynek', variant: 'outline' },
    ],
    stage: 'Etap 1',
  },
  {
    id: '27',
    name: 'Zarządzenie sektora bankowego',
    lastUpdate: '05-06-2022',
    category: 'inne',
    tags: [
      { name: 'Finanse', variant: 'default' },
      { name: 'Banki', variant: 'secondary' },
    ],
    stage: 'Etap 3',
  },
  {
    id: '28',
    name: 'Obwieszczenie o ubezpieczeniach',
    lastUpdate: '28-05-2022',
    category: 'inne',
    tags: [
      { name: 'Finanse', variant: 'secondary' },
      { name: 'Ubezpieczenia', variant: 'outline' },
    ],
    stage: 'Etap 2',
  },
  {
    id: '29',
    name: 'Zarządzenie o papierach wartościowych',
    lastUpdate: '15-04-2022',
    category: 'inne',
    tags: [
      { name: 'Rynek', variant: 'destructive' },
      { name: 'Finanse', variant: 'secondary' },
    ],
    stage: 'Etap 1',
  },
  {
    id: '30',
    name: 'Obwieszczenie o funduszach',
    lastUpdate: '08-03-2022',
    category: 'inne',
    tags: [
      { name: 'Inwestycje', variant: 'secondary' },
      { name: 'Finanse', variant: 'outline' },
    ],
    stage: 'Etap 3',
  },
  {
    id: '31',
    name: 'Ustawa o reformie systemu edukacji',
    lastUpdate: '02-02-2024',
    category: 'ustawy',
    tags: [
      { name: 'Edukacja', variant: 'secondary' },
      { name: 'Innowacje', variant: 'outline' },
    ],
    stage: 'Etap 1',
  },
  {
    id: '32',
    name: 'Ustawa o promocji przedsiębiorczości',
    lastUpdate: '15-01-2024',
    category: 'ustawy',
    tags: [
      { name: 'Biznes', variant: 'default' },
      { name: 'Prawo', variant: 'secondary' },
    ],
    stage: 'Etap 2',
  },
  {
    id: '33',
    name: 'Ustawa o sprawach rodzinnych',
    lastUpdate: '22-12-2023',
    category: 'ustawy',
    tags: [
      { name: 'Rodzina', variant: 'secondary' },
      { name: 'Prawo', variant: 'outline' },
    ],
    stage: 'Etap 3',
  },
  {
    id: '34',
    name: 'Ustawa o zmianie kodeksu cywilnego',
    lastUpdate: '10-11-2023',
    category: 'ustawy',
    tags: [
      { name: 'Prawo', variant: 'destructive' },
      { name: 'Kodeks', variant: 'secondary' },
    ],
    stage: 'Etap 1',
  },
  {
    id: '35',
    name: 'Ustawa o podatku od transakcji finansowych',
    lastUpdate: '18-10-2023',
    category: 'ustawy',
    tags: [
      { name: 'Finanse', variant: 'secondary' },
      { name: 'Podatki', variant: 'outline' },
    ],
    stage: 'Etap 2',
  },
  {
    id: '36',
    name: 'Ustawa o ochronie konkurencji i konsumentów',
    lastUpdate: '05-09-2023',
    category: 'ustawy',
    tags: [
      { name: 'Konkurencja', variant: 'default' },
      { name: 'Ochrona', variant: 'secondary' },
    ],
    stage: 'Etap 3',
  },
  {
    id: '37',
    name: 'Ustawa o energii odnawialnej',
    lastUpdate: '20-08-2023',
    category: 'ustawy',
    tags: [
      { name: 'Ekologia', variant: 'secondary' },
      { name: 'Infrastruktura', variant: 'outline' },
    ],
    stage: 'Etap 1',
  },
  {
    id: '38',
    name: 'Ustawa o ochronie zabytków',
    lastUpdate: '14-07-2023',
    category: 'ustawy',
    tags: [
      { name: 'Kultura', variant: 'destructive' },
      { name: 'Ochrona', variant: 'secondary' },
    ],
    stage: 'Etap 2',
  },
  {
    id: '39',
    name: 'Ustawa o systemie emerytalnym',
    lastUpdate: '30-05-2023',
    category: 'ustawy',
    tags: [
      { name: 'Socjalne', variant: 'secondary' },
      { name: 'Bezpieczeństwo', variant: 'outline' },
    ],
    stage: 'Etap 3',
  },
  {
    id: '40',
    name: 'Rozporządzenie o standardach pracy',
    lastUpdate: '25-10-2023',
    category: 'rozporzadzenia',
    tags: [
      { name: 'Praca', variant: 'secondary' },
      { name: 'Bezpieczeństwo', variant: 'outline' },
    ],
    stage: 'Etap 2',
  },
  {
    id: '41',
    name: 'Rozporządzenie o ochronie środowiska pracy',
    lastUpdate: '12-09-2023',
    category: 'rozporzadzenia',
    tags: [
      { name: 'Ekologia', variant: 'default' },
      { name: 'Bezpieczeństwo', variant: 'secondary' },
    ],
    stage: 'Etap 1',
  },
  {
    id: '42',
    name: 'Rozporządzenie o certyfikacji produktów',
    lastUpdate: '03-08-2023',
    category: 'rozporzadzenia',
    tags: [
      { name: 'Handel', variant: 'secondary' },
      { name: 'Ochrona', variant: 'outline' },
    ],
    stage: 'Etap 3',
  },
  {
    id: '43',
    name: 'Rozporządzenie o procedurach zamówień publicznych',
    lastUpdate: '20-07-2023',
    category: 'rozporzadzenia',
    tags: [
      { name: 'Finanse', variant: 'destructive' },
      { name: 'Budżet', variant: 'secondary' },
    ],
    stage: 'Etap 2',
  },
  {
    id: '44',
    name: 'Rozporządzenie o normach kredytowych',
    lastUpdate: '08-06-2023',
    category: 'rozporzadzenia',
    tags: [
      { name: 'Finanse', variant: 'secondary' },
      { name: 'Banki', variant: 'outline' },
    ],
    stage: 'Etap 1',
  },
  {
    id: '45',
    name: 'Rozporządzenie o standardach transportu',
    lastUpdate: '15-05-2023',
    category: 'rozporzadzenia',
    tags: [
      { name: 'Transport', variant: 'default' },
      { name: 'Infrastruktura', variant: 'secondary' },
    ],
    stage: 'Etap 3',
  },
  {
    id: '46',
    name: 'Rozporządzenie o etykietowaniu produktów',
    lastUpdate: '22-04-2023',
    category: 'rozporzadzenia',
    tags: [
      { name: 'Handel', variant: 'secondary' },
      { name: 'Ochrona', variant: 'outline' },
    ],
    stage: 'Etap 2',
  },
  {
    id: '47',
    name: 'Rozporządzenie o znaczeniu regulacyjnym',
    lastUpdate: '10-03-2023',
    category: 'rozporzadzenia',
    tags: [
      { name: 'Prawo', variant: 'destructive' },
      { name: 'Bezpieczeństwo', variant: 'secondary' },
    ],
    stage: 'Etap 1',
  },
  {
    id: '48',
    name: 'Rozporządzenie o rynku kapitałowym',
    lastUpdate: '25-02-2023',
    category: 'rozporzadzenia',
    tags: [
      { name: 'Finanse', variant: 'secondary' },
      { name: 'Rynek', variant: 'outline' },
    ],
    stage: 'Etap 3',
  },
  {
    id: '49',
    name: 'Rozporządzenie o harmonizacji technicznej',
    lastUpdate: '08-01-2023',
    category: 'rozporzadzenia',
    tags: [
      { name: 'Technologia', variant: 'default' },
      { name: 'Infrastruktura', variant: 'secondary' },
    ],
    stage: 'Etap 2',
  },
  {
    id: '50',
    name: 'Zarządzenie dotyczące polityki kadrowej',
    lastUpdate: '18-12-2022',
    category: 'inne',
    tags: [
      { name: 'Praca', variant: 'secondary' },
      { name: 'Organizacja', variant: 'outline' },
    ],
    stage: 'Etap 1',
  },
  {
    id: '51',
    name: 'Obwieszczenie o zmianach w prawie karnym',
    lastUpdate: '05-11-2022',
    category: 'inne',
    tags: [
      { name: 'Prawo', variant: 'destructive' },
      { name: 'Bezpieczeństwo', variant: 'secondary' },
    ],
    stage: 'Etap 3',
  },
  {
    id: '52',
    name: 'Zarządzenie o standardach usług publicznych',
    lastUpdate: '20-10-2022',
    category: 'inne',
    tags: [
      { name: 'Organizacja', variant: 'secondary' },
      { name: 'Prawo', variant: 'outline' },
    ],
    stage: 'Etap 2',
  },
  {
    id: '53',
    name: 'Obwieszczenie o wdrożeniu dyrektywy UE',
    lastUpdate: '15-09-2022',
    category: 'inne',
    tags: [
      { name: 'Prawo', variant: 'default' },
      { name: 'Międzynarodowe', variant: 'secondary' },
    ],
    stage: 'Etap 1',
  },
  {
    id: '54',
    name: 'Zarządzenie o ochronie informacji niejawnych',
    lastUpdate: '22-08-2022',
    category: 'inne',
    tags: [
      { name: 'Bezpieczeństwo', variant: 'secondary' },
      { name: 'Prywatność', variant: 'outline' },
    ],
    stage: 'Etap 3',
  },
  {
    id: '55',
    name: 'Obwieszczenie o zmianach kodeksu postępowania',
    lastUpdate: '10-07-2022',
    category: 'inne',
    tags: [
      { name: 'Prawo', variant: 'destructive' },
      { name: 'Kodeks', variant: 'secondary' },
    ],
    stage: 'Etap 2',
  },
  {
    id: '56',
    name: 'Zarządzenie o współpracy międzynarodowej',
    lastUpdate: '25-06-2022',
    category: 'inne',
    tags: [
      { name: 'Międzynarodowe', variant: 'secondary' },
      { name: 'Prawo', variant: 'outline' },
    ],
    stage: 'Etap 1',
  },
  {
    id: '57',
    name: 'Obwieszczenie o reformie administracji',
    lastUpdate: '12-05-2022',
    category: 'inne',
    tags: [
      { name: 'Organizacja', variant: 'default' },
      { name: 'Prawo', variant: 'secondary' },
    ],
    stage: 'Etap 3',
  },
  {
    id: '58',
    name: 'Zarządzenie o bezpieczeństwie cybernetycznym',
    lastUpdate: '28-04-2022',
    category: 'inne',
    tags: [
      { name: 'Bezpieczeństwo', variant: 'secondary' },
      { name: 'Technologia', variant: 'outline' },
    ],
    stage: 'Etap 2',
  },
  {
    id: '59',
    name: 'Obwieszczenie o równości i niedyskryminacji',
    lastUpdate: '15-03-2022',
    category: 'inne',
    tags: [
      { name: 'Socjalne', variant: 'destructive' },
      { name: 'Prawo', variant: 'secondary' },
    ],
    stage: 'Etap 1',
  },
];
