export const lawsData = [
  {
    id: '1',
    name: 'Ustawa o przeciwdziałaniu pornografii dziecięcej',
    title: 'Ustawa o przeciwdziałaniu pornografii dziecięcej',
    lastUpdate: '19-08-2024',
    createdDate: '2024-08-19',
    category: 'ustawy',
    projectType: 'Projekty założeń projektów ustaw',
    superCategory: 'prawo_krajowe',
    location: 'Warszawa',
    locationCode: 'WAW',
    tags: [
      { name: 'Bezpieczeństwo', variant: 'secondary' },
      { name: 'Dzieci', variant: 'outline' },
    ],
    stage: 'Etap 2',
    applicant: 'Sejm RP',
    legislativeNumber: 'PLS-2024-001',
    euLaw: true,
    constitutionalCourt: false,
    lawBased: false,
    separateProcess: false,
    journalPublished: true,
    sejm: true,
  },
  {
    id: '2',
    name: 'Ustawa o ochronie danych osobowych',
    title: 'Ustawa o ochronie danych osobowych',
    lastUpdate: '15-07-2024',
    createdDate: '2024-07-15',
    category: 'ustawy',
    projectType: 'Projekty ustaw',
    superCategory: 'prawo_krajowe',
    location: 'Warszawa',
    locationCode: 'WAW',
    tags: [
      { name: 'Bezpieczeństwo', variant: 'destructive' },
      { name: 'Prywatność', variant: 'default' },
    ],
    stage: 'Etap 1',
    applicant: 'Sejm RP',
    legislativeNumber: 'PLS-2024-002',
    euLaw: true,
    constitutionalCourt: false,
    lawBased: true,
    separateProcess: false,
    journalPublished: false,
    sejm: true,
  },
  {
    id: '3',
    name: 'Ustawa o edukacji',
    title: 'Ustawa o edukacji',
    lastUpdate: '20-06-2024',
    createdDate: '2024-06-20',
    category: 'ustawy',
    projectType: 'Projekty ustaw',
    superCategory: 'prawo_krajowe',
    location: 'Kraków',
    locationCode: 'KRK',
    tags: [
      { name: 'Edukacja', variant: 'secondary' },
    ],
    stage: 'Etap 3',
    applicant: 'Rząd RP',
    legislativeNumber: 'PLS-2024-003',
    euLaw: false,
    constitutionalCourt: true,
    lawBased: false,
    separateProcess: false,
    journalPublished: true,
    sejm: true,
  },
  {
    id: '4',
    name: 'Ustawa o ochronie konsumentów',
    title: 'Ustawa o ochronie konsumentów',
    lastUpdate: '12-05-2024',
    createdDate: '2024-05-12',
    category: 'ustawy',
    projectType: 'Projekty ustaw',
    superCategory: 'prawo_krajowe',
    location: 'Wrocław',
    locationCode: 'WRO',
    tags: [
      { name: 'Ochrona', variant: 'secondary' },
      { name: 'Handel', variant: 'outline' },
    ],
    stage: 'Etap 2',
    applicant: 'Sejm RP',
    legislativeNumber: 'PLS-2024-004',
    euLaw: true,
    constitutionalCourt: false,
    lawBased: false,
    separateProcess: true,
    journalPublished: true,
    sejm: false,
  },
  {
    id: '5',
    name: 'Ustawa o zdrowiu publicznym',
    title: 'Ustawa o zdrowiu publicznym',
    lastUpdate: '08-04-2024',
    createdDate: '2024-04-08',
    category: 'ustawy',
    projectType: 'Projekty ustaw',
    superCategory: 'prawo_krajowe',
    location: 'Poznań',
    locationCode: 'POZ',
    tags: [
      { name: 'Zdrowie', variant: 'destructive' },
      { name: 'Medycyna', variant: 'default' },
    ],
    stage: 'Etap 1',
    applicant: 'Rząd RP',
    legislativeNumber: 'PLS-2024-005',
    euLaw: false,
    constitutionalCourt: false,
    lawBased: true,
    separateProcess: false,
    journalPublished: false,
    sejm: true,
  },
  {
    id: '6',
    name: 'Ustawa o bezpieczeństwie alimentarnym',
    title: 'Ustawa o bezpieczeństwie alimentarnym',
    lastUpdate: '03-03-2024',
    createdDate: '2024-03-03',
    category: 'ustawy',
    projectType: 'Projekty założeń projektów ustaw',
    superCategory: 'prawo_krajowe',
    location: 'Gdańsk',
    locationCode: 'GDA',
    tags: [
      { name: 'Zdrowie', variant: 'secondary' },
      { name: 'Ochrona', variant: 'outline' },
    ],
    stage: 'Etap 3',
    applicant: 'Sejm RP',
    legislativeNumber: 'PLS-2024-006',
    euLaw: true,
    constitutionalCourt: false,
    lawBased: false,
    separateProcess: false,
    journalPublished: true,
    sejm: true,
  },
  {
    id: '7',
    name: 'Ustawa o ochronie środowiska',
    title: 'Ustawa o ochronie środowiska',
    lastUpdate: '25-02-2024',
    createdDate: '2024-02-25',
    category: 'ustawy',
    projectType: 'Projekty ustaw',
    superCategory: 'prawo_krajowe',
    location: 'Warszawa',
    locationCode: 'WAW',
    tags: [
      { name: 'Ekologia', variant: 'secondary' },
      { name: 'Ochrona', variant: 'outline' },
    ],
    stage: 'Etap 2',
    applicant: 'Prezydent RP',
    legislativeNumber: 'PLS-2024-007',
    euLaw: true,
    constitutionalCourt: false,
    lawBased: true,
    separateProcess: false,
    journalPublished: true,
    sejm: true,
  },
  {
    id: '8',
    name: 'Ustawa o regulacji transportu',
    title: 'Ustawa o regulacji transportu',
    lastUpdate: '18-01-2024',
    createdDate: '2024-01-18',
    category: 'ustawy',
    projectType: 'Projekty ustaw',
    superCategory: 'prawo_krajowe',
    location: 'Łódź',
    locationCode: 'ŁDZ',
    tags: [
      { name: 'Transport', variant: 'default' },
      { name: 'Infrastruktura', variant: 'secondary' },
    ],
    stage: 'Etap 1',
    applicant: 'Rząd RP',
    legislativeNumber: 'PLS-2024-008',
    euLaw: false,
    constitutionalCourt: false,
    lawBased: false,
    separateProcess: true,
    journalPublished: false,
    sejm: true,
  },
  {
    id: '9',
    name: 'Ustawa o świadczeniach rodzinnych',
    title: 'Ustawa o świadczeniach rodzinnych',
    lastUpdate: '10-12-2023',
    createdDate: '2023-12-10',
    category: 'ustawy',
    projectType: 'Projekty ustaw',
    superCategory: 'instytucje_lokalne',
    location: 'Szczecin',
    locationCode: 'SZC',
    tags: [
      { name: 'Socjalne', variant: 'secondary' },
      { name: 'Rodzina', variant: 'outline' },
    ],
    stage: 'Etap 3',
    applicant: 'Sejm RP',
    legislativeNumber: 'PLS-2023-009',
    euLaw: false,
    constitutionalCourt: true,
    lawBased: true,
    separateProcess: false,
    journalPublished: true,
    sejm: true,
  },
  {
    id: '10',
    name: 'Ustawa o zatrudnieniu i pracy',
    title: 'Ustawa o zatrudnieniu i pracy',
    lastUpdate: '05-11-2023',
    createdDate: '2023-11-05',
    category: 'ustawy',
    projectType: 'Projekty ustaw',
    superCategory: 'instytucje_lokalne',
    location: 'Warszawa',
    locationCode: 'WAW',
    tags: [
      { name: 'Praca', variant: 'destructive' },
      { name: 'Socjalne', variant: 'default' },
    ],
    stage: 'Etap 2',
    applicant: 'Rząd RP',
    legislativeNumber: 'PLS-2023-010',
    euLaw: true,
    constitutionalCourt: false,
    lawBased: false,
    separateProcess: false,
    journalPublished: true,
    sejm: false,
  },
];
